// Debe coincidir con MODULOS_DISPONIBLES en backend/src/utils/modulos.js
export const MODULOS_DISPONIBLES = [
  { clave: 'copiloto_ia',          nombre: 'Copiloto IA' },
  { clave: 'piar',                 nombre: 'PIAR' },
  { clave: 'observador_academico', nombre: 'Observador Académico' },
  { clave: 'motor_riesgo',         nombre: 'Motor de Riesgo' },
  { clave: 'evaluacion_docentes',  nombre: 'Evaluación Docente' },
  { clave: 'citaciones',           nombre: 'Citaciones' },
  { clave: 'mensajes_masivos',     nombre: 'Mensajes Masivos' },
  { clave: 'gemelo_digital',       nombre: 'Gemelo Digital' },
  { clave: 'planes_mejoramiento',  nombre: 'Planes de Mejoramiento' },
  { clave: 'comparativas',         nombre: 'Comparativas de Períodos' },
  { clave: 'tutor_ia',             nombre: 'Tutor IA (estudiantes)' },
  { clave: 'auditoria',            nombre: 'Auditoría' },
  { clave: 'boletines',            nombre: 'Boletines' },
  { clave: 'institucion_academica',nombre: 'Institución Académica (Grados, Grupos, Semana Académica, Salones)' },
  { clave: 'asignaturas',          nombre: 'Asignaturas (Áreas, Materias, Carga Académica)' },
  { clave: 'cargue_historico',     nombre: 'Cargue de Histórico' },
  { clave: 'cierre_anio_lectivo',  nombre: 'Cierre de Año Lectivo' },
  { clave: 'agenda_gestion',       nombre: 'Agenda Institucional (crear/editar eventos)' },
];
